import type { ShotMeta } from "./types";

/**
 * SHOTS — 샷 선택 UI 메타데이터.
 * slunch-admin.html line 4576-4697 그대로 포팅.
 */
export const SHOTS: ShotMeta[] = [
  { id: 'hero', name: '히어로 크레이빙 클로즈업', type: 'hero',
    purpose: '상세페이지 최상단 메인 이미지. 극접사 크레이빙 샷으로 식욕 자극.',
    maps: '① 영웅 이미지 → hero_image', default: true },
  { id: 'dish', name: '디쉬 항공샷 (90° 오버헤드)', type: 'dish',
    purpose: '90° 위에서 내려다본 완성 디쉬 단독 샷. 텍스트 여백 확보.',
    maps: '③ 디쉬 항공샷 → feature_image', default: true },
  { id: 'cooking', name: '조리공정', type: 'cooking',
    purpose: '밝고 즐거운 조리 과정. 장갑 낀 손과 재료, 맛있는 음식을 만드는 장면.',
    maps: '④ 조리공정 → process_image', default: true },
  { id: 'ingredientBanner', name: '재료 배너 — 조각 스틸라이프', type: 'ingredient',
    purpose: '핵심 원재료를 조각처럼 쌓아올린 아트 스틸라이프. 단색 배경, 긴장감 있는 밸런싱 구도.',
    maps: '⑤ 재료배너 → ingredient_image', default: true },
  { id: 'ingredientGrid', name: '재료 상세 — 3×3 매거진 그리드', type: 'ingredient',
    purpose: '각 원재료를 서로 다른 컬러 배경 위에 1종씩 배치한 3×3 그리드.',
    maps: '⑤ 재료상세 → ingredient_detail_image', default: true },
  { id: 'servingBanner', name: '섭취 방법 배너 (누끼 리프트샷)', type: 'serving',
    purpose: '흰 배경 누끼. 접시에서 한입 분량을 식기로 집어올린 순간 포착. 식욕 자극 + 텍스트 배치 용이.',
    maps: '⑧ 섭취 방법 → serving_center_image', default: true },
  { id: 'servingThumb1', name: '섭취 썸네일 ① 핸드헬드', type: 'eating',
    purpose: '손으로 그릇 들고 있는 캐주얼 라이프스타일 컷.',
    maps: '⑧ 섭취 방법 → serving_1_image', default: true },
  { id: 'servingThumb2', name: '섭취 썸네일 ② 젓가락 누끼', type: 'eating',
    purpose: '단색 배경, 식기로 한입 찍어올림. 색다른 소스 디핑.',
    maps: '⑧ 섭취 방법 → serving_2_image', default: true },
  { id: 'servingThumb3', name: '섭취 썸네일 ③ 매크로 텍스처', type: 'eating',
    purpose: '극접사. 식기가 음식 질감을 파고드는 순간.',
    maps: '⑧ 섭취 방법 → serving_3_image', default: true },
  { id: 'servingThumb4', name: '섭취 썸네일 ④ 치즈 풀', type: 'eating',
    purpose: '들어올릴 때 치즈가 길게 늘어나는 치즈 퐁듀 스타일.',
    maps: '⑧ 섭취 방법 → serving_4_image', default: true },
  { id: 'servingThumb5', name: '섭취 썸네일 ⑤ 캐주얼 다이닝', type: 'eating',
    purpose: '밝은 배경, 손으로 직접 집어먹는 친밀하고 즐거운 순간.',
    maps: '⑧ 섭취 방법 → serving_5_image', default: true },
  { id: 'reveal', name: '리빌 시그니처', type: 'reveal',
    purpose: '감성적 제품+음식 정물. 브랜드 마무리 느낌.',
    maps: '⑩ 리빌 메시지 → reveal_image', default: true },
  { id: 'ending', name: '제품 엔딩샷', type: 'package',
    purpose: 'FAQ 아래 마무리. 패키지+내용물 병렬 상업 촬영. 구매 전환 유도.',
    maps: '⑬ 제품 정보 → ending_image', default: true },
  { id: 'sharing', name: '함께 나눠먹기', type: 'serving',
    purpose: '두 사람이 테이블에서 제품을 함께 나눠먹는 라이프스타일 장면.',
    maps: '⑧ 섭취 방법 → sharing_image', default: true },
  { id: 'gathering', name: '다같이 모여먹기', type: 'serving',
    purpose: '여러 명이 함께 모여 음식을 나눠먹는 밝고 즐거운 파티/모임 장면.',
    maps: '⑧ 섭취 방법 → gathering_image', default: true },
];
