import type { FobData, StyleEntry } from "./types";

/**
 * PRODUCT_STYLE_MAP — 제품별 자동 스타일 매핑.
 * slunch-admin.html line 5134-5527 그대로 포팅.
 *
 * 규칙: 구체 → 일반 순서. 모든 값 단일 확정. 중복표현 금지.
 * 기본: 재활용 플라스틱 테이블 + 파이버글래스 캠트레이 위 그릇.
 * 그릇 색상: 음식 색상의 보색/대비색.
 */
export const PRODUCT_STYLE_MAP: StyleEntry[] = [
  // === 단호박 초코 케이크 (노란+갈색 음식 → 네이비 볼) ===
  {
    match: (fob) => /단호박.*초코|pumpkin.*choco/i.test(fob.nameKr + fob.nameEn),
    plate: '네이비 파이버글래스 캠트레이 위 아이보리 라운드 디저트 플레이트',
    utensil: '디저트 포크',
    noUtensil: '젓가락 금지',
    garnish: '카카오파우더 더스팅',
    noGarnish: '참깨 금지',
    bgColor: '재활용 플라스틱 옐로우 테이블',
    wallColor: '크림화이트 매트 벽',
    foodDesc: 'dark chocolate brownie cake with chunky orange pumpkin pieces in cross-section, purple and yellow marbled glaze on top, rich moist texture',
    eatingTool: 'dessert fork',
    eatingAction: 'fork cutting into cake slice, moist crumb visible at the cut',
    liftTool: 'dessert fork',
    liftAction: 'fork lifting a wedge of cake, pumpkin chunk and chocolate layer visible in cross-section, crumbs falling',
    cookAction: 'hands folding pumpkin puree into chocolate batter in a mixing bowl, swirl of orange and brown',
    ingredients: 'pumpkin, dark chocolate, cocoa powder, flour, sugar, coconut oil',
    pullAction: 'rich dark chocolate ganache dripping in thick glossy ribbons between the fork and the cake slice',
  },
  // === 말차 케이크 ===
  {
    match: (fob) => /말차|matcha/i.test(fob.nameKr + fob.nameEn),
    plate: '테라코타 파이버글래스 캠트레이 위 크림화이트 라운드 플레이트',
    utensil: '디저트 포크',
    noUtensil: '젓가락 금지',
    garnish: '말차파우더 더스팅',
    noGarnish: '참깨 금지',
    bgColor: '재활용 플라스틱 세이지그린 테이블',
    wallColor: '크림화이트 매트 벽',
    foodDesc: 'vibrant green matcha sponge cake, checkerboard cross-section with purple sweet bean paste, marbled matcha glaze on top',
    eatingTool: 'dessert fork',
    eatingAction: 'fork pressing into soft matcha sponge, green crumb separating cleanly',
    liftTool: 'dessert fork',
    liftAction: 'fork lifting a slice revealing green-and-purple checkerboard layers, soft crumb texture',
    cookAction: 'hands sifting matcha powder into batter, vibrant green cloud of powder mid-air',
    ingredients: 'matcha powder, flour, sugar, eggs, butter, sweet red bean paste, cream',
    pullAction: 'matcha cream oozing from between green sponge layers, soft pale green cream stretching',
  },
  // === 블루베리 타르트 ===
  {
    match: (fob) => /tart|타르트/i.test(fob.nameKr + fob.nameEn + fob.category) && /blueberry|블루베리/i.test(fob.nameKr + fob.nameEn),
    plate: '앰버골드 파이버글래스 캠트레이 위 크림화이트 라운드 플레이트',
    utensil: '디저트 포크',
    noUtensil: '젓가락 금지',
    garnish: '슈가파우더 더스팅',
    noGarnish: '참깨 금지',
    bgColor: '재활용 플라스틱 라벤더 테이블',
    wallColor: '아이보리 매트 벽',
    foodDesc: 'golden crispy tart crust filled with glossy dark berry compote, fresh blueberries piled on top',
    eatingTool: 'dessert fork',
    eatingAction: 'fork breaking through crispy tart crust, berry compote oozing from the crack',
    liftTool: 'dessert fork',
    liftAction: 'fork lifting a wedge of tart, blueberry compote dripping from flaky crust edge',
    cookAction: 'hands pressing tart dough into a fluted mold, raw dough smooth under fingertips',
    ingredients: 'blueberries, flour, butter, sugar, eggs, lemon zest, vanilla',
    pullAction: 'dark purple blueberry compote oozing and dripping from the cracked tart crust, glossy berry juice trailing',
  },
  // === 복숭아 타르트 ===
  {
    match: (fob) => /tart|타르트/i.test(fob.nameKr + fob.nameEn + fob.category) && /peach|복숭아/i.test(fob.nameKr + fob.nameEn),
    plate: '코발트블루 파이버글래스 캠트레이 위 크림화이트 라운드 플레이트',
    utensil: '디저트 포크',
    noUtensil: '젓가락 금지',
    garnish: '민트잎 1장',
    noGarnish: '참깨 금지',
    bgColor: '재활용 플라스틱 피치핑크 테이블',
    wallColor: '쿨화이트 매트 벽',
    foodDesc: 'golden flaky tart crust with glazed peach slices arranged in spiral, glossy fruit glaze',
    eatingTool: 'dessert fork',
    eatingAction: 'fork sliding under a glazed peach slice, golden crust crumbling at the edge',
    liftTool: 'dessert fork',
    liftAction: 'fork lifting a section of tart with peach slice on top, glaze stretching, flaky crust layers visible',
    cookAction: 'hands arranging thin peach slices in spiral pattern inside a tart shell, precise placement',
    ingredients: 'peaches, flour, butter, sugar, eggs, vanilla, apricot glaze',
    pullAction: 'golden apricot glaze stretching and dripping from the lifted tart slice, glossy peach juice trailing',
  },
  // === 일반 타르트 ===
  {
    match: (fob) => /tart|타르트/i.test(fob.nameKr + fob.nameEn + fob.category),
    plate: '올리브그린 파이버글래스 캠트레이 위 크림화이트 라운드 플레이트',
    utensil: '디저트 포크',
    noUtensil: '젓가락 금지',
    garnish: '슈가파우더 더스팅',
    noGarnish: '참깨 금지',
    bgColor: '재활용 플라스틱 크림베이지 테이블',
    wallColor: '라이트그레이 매트 벽',
    foodDesc: 'golden crispy tart crust, glossy fruit filling, artisan baked texture',
    eatingTool: 'dessert fork',
    eatingAction: 'fork piercing through crispy tart crust, filling visible at the break',
    liftTool: 'dessert fork',
    liftAction: 'fork lifting a triangular tart wedge, filling oozing from the cut side',
    cookAction: 'hands crimping tart dough edges with fingertips, raw pastry shell taking shape',
    ingredients: 'flour, butter, sugar, eggs, fresh fruit, vanilla, cream',
    pullAction: 'glossy fruit glaze dripping from the lifted tart wedge, flaky crust crumbling',
  },
  // === 일반 케이크 (pancake 제외) ===
  {
    match: (fob) => /(?<!pan)cake|케이크/i.test(fob.nameKr + fob.nameEn + fob.category),
    plate: '올리브그린 파이버글래스 캠트레이 위 크림화이트 라운드 플레이트',
    utensil: '디저트 포크',
    noUtensil: '젓가락 금지',
    garnish: '슈가파우더 더스팅',
    noGarnish: '참깨 금지',
    bgColor: '재활용 플라스틱 크림베이지 테이블',
    wallColor: '라이트그레이 매트 벽',
    foodDesc: 'moist layered cake, clean cross-section visible, rich frosting on top',
    eatingTool: 'dessert fork',
    eatingAction: 'fork pressing into moist cake layers, frosting smearing slightly on the tines',
    liftTool: 'dessert fork',
    liftAction: 'fork lifting a bite of layered cake, frosting and sponge layers clearly visible',
    cookAction: 'hands smoothing frosting on a cake layer with an offset spatula, even strokes',
    ingredients: 'flour, sugar, butter, eggs, cream, vanilla, baking powder',
    pullAction: 'thick cream frosting stretching between cake layers as fork lifts a slice, moist crumb visible',
  },
  // === 초코바 ===
  {
    match: (fob) => /초코바|choco bar/i.test(fob.nameKr + fob.nameEn),
    plate: '아이보리 파이버글래스 캠트레이',
    utensil: '없음',
    noUtensil: '포크 금지',
    garnish: '으깬 땅콩 약간',
    noGarnish: '허브 금지',
    bgColor: '재활용 플라스틱 다크브라운 테이블',
    wallColor: '크림베이지 매트 벽',
    foodDesc: 'snapped chocolate bar revealing creamy peanut butter filling inside, glossy chocolate coating, cross-section visible',
    eatingTool: 'bare hand',
    eatingAction: 'hand snapping a chocolate bar in half, peanut butter filling stretching between the two halves',
    liftTool: 'hand',
    liftAction: 'hand holding a snapped chocolate bar piece at eye level, cross-section of peanut butter filling exposed, chocolate coating glistening',
    cookAction: 'hands pouring melted chocolate over a lined mold filled with peanut butter, glossy chocolate stream',
    ingredients: 'dark chocolate, peanut butter, cocoa butter, coconut oil, sea salt, vanilla',
    pullAction: 'thick peanut butter filling stretching between two snapped halves of the chocolate bar, glossy chocolate shell cracking',
  },
  // === 피자 ===
  {
    match: (fob) => /피자|pizza/i.test(fob.nameKr + fob.nameEn),
    plate: '옐로우 파이버글래스 캠트레이',
    utensil: '없음',
    noUtensil: '젓가락 금지',
    garnish: '칠리플레이크 약간',
    noGarnish: '참깨 금지',
    bgColor: '재활용 플라스틱 레드 테이블',
    wallColor: '오프화이트 매트 벽',
    foodDesc: 'triangular pizza slice with melted vegan mozzarella stretching, vegan pepperoni rounds, golden crispy crust edge',
    eatingTool: 'bare hand',
    eatingAction: 'hand lifting a pizza slice from the tray, melted cheese stretching in long strings from the slice to the remaining pie',
    liftTool: 'hand',
    liftAction: 'hand pulling a pizza slice upward, vegan mozzarella stretching in dramatic strings, pepperoni and toppings sliding',
    cookAction: 'hands stretching raw pizza dough mid-air, flour dusting off, round shape forming',
    ingredients: 'pizza dough, vegan mozzarella, vegan pepperoni, tomato sauce, olive oil, oregano, basil',
    pullAction: 'melted vegan mozzarella stretching in long dramatic strings as pizza slice is lifted, golden cheese pull',
  },
  // === 시금치 뇨끼 ===
  {
    match: (fob) => /뇨끼|gnocchi/i.test(fob.nameKr + fob.nameEn),
    plate: '테라코타 파이버글래스 캠트레이 위 크림화이트 넓은 파스타볼',
    utensil: '포크',
    noUtensil: '젓가락 금지',
    garnish: '올리브오일 드리즐',
    noGarnish: '참깨 금지',
    bgColor: '재활용 플라스틱 세이지그린 테이블',
    wallColor: '웜화이트 매트 벽',
    foodDesc: 'pillowy soft potato gnocchi in creamy white sauce with green spinach flecks, steaming hot',
    eatingTool: 'fork',
    eatingAction: 'fork spearing two gnocchi pieces, creamy sauce coating them, spinach fleck visible',
    liftTool: 'fork',
    liftAction: 'fork lifting gnocchi from creamy sauce, sauce dripping back into bowl, pillowy texture visible',
    cookAction: 'hands rolling small potato dough pieces on a fork-ridged gnocchi board, creating classic grooved pattern',
    ingredients: 'potatoes, flour, spinach, cream, garlic, parmesan, olive oil, nutmeg',
    pullAction: 'thick creamy white sauce stretching and dripping from gnocchi on the fork, pillowy soft texture',
  },
  // === 매생이 크림 펜네 ===
  {
    match: (fob) => /펜네|penne/i.test(fob.nameKr + fob.nameEn),
    plate: '코랄핑크 파이버글래스 캠트레이 위 아이보리 넓은 파스타볼',
    utensil: '포크',
    noUtensil: '젓가락 금지',
    garnish: '선드라이 토마토 몇 조각',
    noGarnish: '참깨 금지',
    bgColor: '재활용 플라스틱 옐로우골드 테이블',
    wallColor: '쿨그레이 매트 벽',
    foodDesc: 'penne pasta coated in creamy green maesaengi seaweed sauce, specks of sun-dried tomato, vibrant green color',
    eatingTool: 'fork',
    eatingAction: 'fork twirling penne tubes, green cream sauce coating each tube, sun-dried tomato piece caught in tines',
    liftTool: 'fork',
    liftAction: 'fork lifting penne from bowl, creamy green sauce dripping, tubes stacked on tines',
    cookAction: 'hands stirring bright green maesaengi cream sauce into penne in a saucepan, wooden spoon mid-stir',
    ingredients: 'penne pasta, maesaengi seaweed, cream, garlic, sun-dried tomatoes, olive oil, parmesan',
    pullAction: 'green maesaengi cream sauce coating and dripping from penne tubes on the fork, vibrant green sauce trailing',
  },
  // === 매생이 트러플 리조또 ===
  {
    match: (fob) => /리조또|risotto/i.test(fob.nameKr + fob.nameEn),
    plate: '차콜그레이 파이버글래스 캠트레이 위 크림화이트 얕은 볼',
    utensil: '숟가락',
    noUtensil: '젓가락 금지',
    garnish: '트러플오일 드리즐',
    noGarnish: '참깨 금지',
    bgColor: '재활용 플라스틱 크래프트브라운 테이블',
    wallColor: '웜화이트 매트 벽',
    foodDesc: 'creamy risotto with visible maesaengi seaweed strands, truffle oil glistening on surface, fluffy rice texture',
    eatingTool: 'spoon',
    eatingAction: 'spoon scooping a mound of creamy risotto, seaweed strands trailing from the spoon, truffle oil sheen',
    liftTool: 'spoon',
    liftAction: 'spoon lifting a scoop of risotto above the bowl, creamy rice dripping, maesaengi strands dangling',
    cookAction: 'hands ladling warm broth into risotto rice in a wide pan, stirring with wooden spoon, steam rising',
    ingredients: 'arborio rice, maesaengi seaweed, truffle oil, onion, garlic, vegetable broth, parmesan, butter',
    pullAction: 'creamy risotto stretching from the spoon in a thick glossy ribbon, truffle oil glistening on surface',
  },
  // === 김치볶음밥 ===
  {
    match: (fob) => /볶음밥|fried rice/i.test(fob.nameKr + fob.nameEn),
    plate: '코발트블루 파이버글래스 캠트레이 위 코발트블루 세라믹볼',
    utensil: '숟가락',
    noUtensil: '포크 금지',
    garnish: '참깨 약간',
    noGarnish: '허브 금지',
    bgColor: '재활용 플라스틱 주황 테이블',
    wallColor: '크림화이트 매트 벽',
    foodDesc: 'vibrant red-orange kimchi fried rice, visible kimchi pieces and vegetables mixed throughout, steaming hot',
    eatingTool: 'spoon',
    eatingAction: 'spoon scooping a heaped mound of fried rice, kimchi pieces and rice grains visible on the spoon',
    liftTool: 'spoon',
    liftAction: 'spoon lifting a generous scoop of kimchi fried rice above bowl, loose grains falling back, steam rising',
    cookAction: 'hands tossing fried rice in a hot wok, grains mid-air, red kimchi pieces visible among the rice',
    ingredients: 'rice, kimchi, gochugaru, sesame oil, garlic, scallions, vegetables, sesame seeds',
    pullAction: 'runny egg yolk bursting and flowing over the fried rice as spoon breaks it, golden yolk streaming',
  },
  // === 김치캔 ===
  {
    match: (fob) => /김치캔|kimchi can/i.test(fob.nameKr + fob.nameEn),
    plate: '코발트블루 파이버글래스 캠트레이 위 코발트블루 세라믹볼',
    utensil: '젓가락',
    noUtensil: '포크 금지',
    garnish: '잘게 썬 김',
    noGarnish: '허브 금지',
    bgColor: '재활용 플라스틱 레드 테이블',
    wallColor: '오프화이트 매트 벽',
    foodDesc: 'glistening stir-fried kimchi with visible napa cabbage leaves, red pepper coating, slightly caramelized edges',
    eatingTool: 'chopsticks',
    eatingAction: 'chopsticks gripping a folded piece of kimchi, red pepper sauce glistening, napa cabbage leaf texture visible',
    liftTool: 'chopsticks',
    liftAction: 'chopsticks lifting a long piece of kimchi above the bowl, sauce dripping, cabbage ribs visible through translucent red coating',
    cookAction: 'hands stir-frying kimchi in a hot pan, tongs flipping caramelized cabbage pieces, red oil sizzling',
    ingredients: 'napa cabbage kimchi, gochugaru, garlic, ginger, scallions, sesame oil, sea salt',
    pullAction: 'glistening red kimchi strands trailing from chopsticks, glossy chili oil dripping, fermented cabbage texture',
  },
  // === 김치전 ===
  {
    match: (fob) => /김치전|pancake/i.test(fob.nameKr + fob.nameEn),
    plate: '네이비 파이버글래스 캠트레이 위 네이비 넓은 접시',
    utensil: '젓가락',
    noUtensil: '포크 금지',
    garnish: '간장 디핑소스 작은 종지',
    noGarnish: '허브 금지',
    bgColor: '재활용 플라스틱 옐로우 테이블',
    wallColor: '크림화이트 매트 벽',
    foodDesc: 'golden-brown crispy kimchi pancake, visible red kimchi pieces throughout, crispy edges, cut into wedges',
    eatingTool: 'chopsticks',
    eatingAction: 'chopsticks picking up a triangular wedge of pancake, dipping into soy sauce dish, crispy edge visible',
    altDipAction: 'chopsticks dipping a crispy pancake wedge into a small dish of spicy cheongyang mayo sauce, creamy green-speckled sauce coating the edge',
    liftTool: 'chopsticks',
    liftAction: 'chopsticks lifting a pancake wedge, crispy golden underside revealed, red kimchi pieces poking through batter',
    cookAction: 'hands spreading kimchi pancake batter in a hot oiled pan, batter sizzling and bubbling at the edges',
    orefFood: 'https://cdn.midjourney.com/u/c9cf7459-fae9-4494-8934-6ad112b91e5a/060320b9151185e5363ac861be31ca0b61ed6555c43a6c585d7e3f5ee5cb15eb.png',
    orefPackage: 'https://cdn.midjourney.com/u/c9cf7459-fae9-4494-8934-6ad112b91e5a/6ee87315f6654c3490181ec2f468b5e009dfb9016f5e18157814175eb1f70a87.png',
    ingredients: 'napa cabbage, scallions, garlic, ginger, gochugaru, flour, sesame seeds, sesame oil',
    pullAction: 'melted cheese stretching in long golden strands as chopsticks lift a crispy pancake wedge, cheese fondue style',
  },
  // === 김치칼국수 ===
  {
    match: (fob) => /칼국수|kalguksu|noodle/i.test(fob.nameKr + fob.nameEn),
    plate: '코발트블루 파이버글래스 캠트레이 위 크림화이트 큰 국물볼',
    utensil: '젓가락',
    noUtensil: '포크 금지',
    garnish: '잘게 썬 대파',
    noGarnish: '허브 금지',
    bgColor: '재활용 플라스틱 크림화이트 테이블',
    wallColor: '라이트블루그레이 매트 벽',
    foodDesc: 'thick hand-cut wheat noodles in red kimchi broth, visible vegetables floating, steaming hot soup',
    eatingTool: 'chopsticks',
    eatingAction: 'chopsticks lifting a tangle of thick noodles from red broth, noodles draping down into the soup, steam rising',
    liftTool: 'chopsticks',
    liftAction: 'chopsticks pulling thick noodles high above the bowl, broth dripping, vegetables clinging to the noodle strands',
    cookAction: 'hands slicing fresh dough into thick noodle strips with a knife on a floured cutting board, neat rows forming',
    ingredients: 'wheat flour noodles, kimchi, zucchini, potato, scallions, garlic, anchovy broth, chili flakes',
    pullAction: 'thick hand-cut noodles stretching and dangling from chopsticks high above the bowl, red broth dripping',
  },
  // === 주먹밥 ===
  {
    match: (fob) => /주먹밥|rice ball|삼각김밥/i.test(fob.nameKr + fob.nameEn),
    plate: '올리브그린 파이버글래스 캠트레이 위 올리브그린 작은 접시',
    utensil: '없음',
    noUtensil: '젓가락 금지',
    garnish: '참깨 약간',
    noGarnish: '허브 금지',
    bgColor: '재활용 플라스틱 크림베이지 테이블',
    wallColor: '라이트그레이 매트 벽',
    foodDesc: 'triangular rice ball, compact shape, visible filling ingredients on surface, golden toasted exterior',
    eatingTool: 'bare hand',
    eatingAction: 'hand holding a rice ball with a bite taken out, filling visible inside the bite mark',
    liftTool: 'hand',
    liftAction: 'hand holding a rice ball at eye level, bite taken revealing colorful filling inside, sesame seeds on surface',
    cookAction: 'hands pressing and shaping warm rice into a triangle, nori sheet wrapping around the base',
    ingredients: 'rice, nori seaweed, sesame seeds, sesame oil, salt, mixed fillings',
    pullAction: 'rice ball broken in half revealing colorful filling inside, rice grains and filling spilling out between the two halves',
  },
  // === 소스/드레싱 ===
  {
    match: (fob) => /드레싱|dressing|소스|sauce|랜치|ranch|레몬|lemon|발사믹|balsamic|오리엔탈|oriental|분짜|bun cha/i.test(fob.nameKr + fob.nameEn),
    plate: '코랄핑크 파이버글래스 캠트레이 위 크림화이트 디핑종지',
    utensil: '없음',
    noUtensil: '젓가락 금지',
    garnish: '디핑용 야채스틱',
    noGarnish: '참깨 금지',
    bgColor: '재활용 플라스틱 라이트그린 테이블',
    wallColor: '아이보리 매트 벽',
    foodDesc: 'squeeze tube bottle standing upright, glossy sauce pooled in small dish, drizzle pattern visible',
    eatingTool: 'vegetable stick',
    eatingAction: 'hand dipping a fresh carrot stick into sauce dish, sauce coating the tip of the vegetable',
    liftTool: 'hand',
    liftAction: 'hand squeezing sauce bottle, thick glossy stream of dressing pouring into dish, pooling pattern forming',
    cookAction: 'hands whisking dressing ingredients in a glass bowl, emulsion forming, herbs and spices visible in the mixture',
    ingredients: 'olive oil, vinegar, lemon, garlic, herbs, mustard, honey, sea salt',
    pullAction: 'thick glossy sauce pouring from squeeze bottle in a slow dramatic drizzle onto vegetable sticks, pooling in dish',
  },
  // === 감태 버터 ===
  {
    match: (fob) => /감태.*버터|gamtae.*butter/i.test(fob.nameKr + fob.nameEn),
    plate: '네이비 파이버글래스 캠트레이',
    utensil: '버터나이프',
    noUtensil: '젓가락 금지',
    garnish: '토스트한 바게트 슬라이스',
    noGarnish: '참깨 금지',
    bgColor: '재활용 플라스틱 올리브그린 테이블',
    wallColor: '웜화이트 매트 벽',
    foodDesc: 'glass jar of golden-green gamtae kelp butter, knife with spread on tip, toasted bread with spread applied',
    eatingTool: 'butter knife',
    eatingAction: 'butter knife spreading gamtae kelp butter on a toasted baguette slice, green-gold butter smearing on golden bread surface',
    liftTool: 'butter knife',
    liftAction: 'butter knife scooping a thick curl of green-gold gamtae butter from the jar, butter texture and kelp flecks visible',
    cookAction: 'hands folding dried gamtae kelp flakes into softened butter in a bowl, green specks distributing throughout golden butter',
    ingredients: 'gamtae kelp, butter, garlic, sea salt, lemon zest, black pepper',
    pullAction: 'golden-green gamtae butter melting and dripping on warm toasted baguette, butter pooling into bread pores',
  },
  // === 매생이 페스토 ===
  {
    match: (fob) => /페스토|pesto/i.test(fob.nameKr + fob.nameEn),
    plate: '테라코타 파이버글래스 캠트레이',
    utensil: '버터나이프',
    noUtensil: '젓가락 금지',
    garnish: '토스트한 바게트 슬라이스',
    noGarnish: '참깨 금지',
    bgColor: '재활용 플라스틱 세이지그린 테이블',
    wallColor: '웜화이트 매트 벽',
    foodDesc: 'glass jar of deep green maesaengi seaweed pesto, knife with spread on tip, toasted bread with spread applied',
    eatingTool: 'butter knife',
    eatingAction: 'butter knife spreading thick green pesto on a toasted baguette slice, deep green paste smearing on crusty bread',
    liftTool: 'butter knife',
    liftAction: 'butter knife lifting a thick scoop of deep green pesto from jar, glossy texture, basil and seaweed flecks visible',
    cookAction: 'hands pulsing fresh maesaengi seaweed with pine nuts and olive oil in a mortar, vivid green paste forming',
    ingredients: 'maesaengi seaweed, pine nuts, garlic, olive oil, parmesan, lemon juice, sea salt',
    pullAction: 'thick deep green pesto spreading on warm toast, glossy oil separating and dripping down the crust edge',
  },
  // === 일반 버터 (fallback) ===
  {
    match: (fob) => /버터|butter/i.test(fob.nameKr + fob.nameEn),
    plate: '네이비 파이버글래스 캠트레이',
    utensil: '버터나이프',
    noUtensil: '젓가락 금지',
    garnish: '토스트한 바게트 슬라이스',
    noGarnish: '참깨 금지',
    bgColor: '재활용 플라스틱 크림베이지 테이블',
    wallColor: '라이트그레이 매트 벽',
    foodDesc: 'glass jar of golden butter spread, knife with spread on tip, toasted bread showing texture',
    eatingTool: 'butter knife',
    eatingAction: 'butter knife spreading golden butter on warm toast, butter melting into the bread surface',
    liftTool: 'butter knife',
    liftAction: 'butter knife scooping a thick curl of golden butter from the jar, smooth creamy texture',
    cookAction: 'hands mixing softened butter with herbs in a bowl, butter smooth and pale yellow',
    ingredients: 'butter, herbs, garlic, sea salt, lemon zest',
    pullAction: 'golden butter melting and dripping on warm toast, butter pooling into bread surface',
  },
];

/** 매칭되는 첫 스타일 반환. 없으면 null. */
export function getProductStyle(fob: FobData | null): StyleEntry | null {
  if (!fob) return null;
  for (const style of PRODUCT_STYLE_MAP) {
    if (style.match(fob)) return style;
  }
  return null;
}
