import type { StoreProduct, SubscribeProduct } from "@/types/product";

export const SEED_STORE_PRODUCT: StoreProduct = {
  product_id: "슬런치 볶음김치 캔",
  hero_image: "",
  hero_title: "밥 위에 한 숟갈, 오늘 점심이 완성됩니다.",
  hero_desc:
    "바쁜 일상 속에서도 맛있는 한 끼를 포기하고 싶지 않은 분들을 위해 슬런치가 준비한 캔 볶음김치입니다.",
  intro_label: "Product introduction",
  intro_title: "매일 먹어도 질리지 않는 절제된 매운맛과 부드러운 감칠맛",
  intro_body: "슬런치 캔 볶음김치는 자극적이지 않으면서도 깊은 맛을 내는 것이 특징입니다.",
  feature_image: "",
  feature_title: "젓갈 없이도 느껴지는 전통 김치의 깊은 풍미",
  feature_body: "대파기름의 온도와 저온 볶음의 시간을 조절해 김치의 숨을 천천히 덜어냈습니다.",
  ingredient_image: "",
  ingredient_detail_image: "",
  ingredient_title: "깨끗한 재료, 정직한 맛",
  ingredient_body: "국내산 배추를 기본으로 마늘, 생강, 파, 고추 등 익숙한 재료만을 사용합니다.",
  process_image: "",
  process_title: "대파기름에 저온으로, 천천히 볶아냅니다",
  process_body: "정성스러운 제조 과정을 거쳐 최고의 맛을 만들어냅니다.",
  process_1: "국내산 배추를 직접 손질하고 3회 세척합니다",
  process_2: "천연 재료로 김치를 숙성합니다 (젓갈 미사용)",
  process_3: "대파기름에 저온 볶음 (풍미 극대화)",
  process_4: "121℃ 고온 살균 후 캔에 밀봉합니다",
  process_5: "금속검출기 및 품질검사 후 출고합니다",
  cert_title: "깨끗한 환경, 믿을 수 있는 인증",
  cert_subtitle: "Certified Quality",
  cert_body: "직접 먹어본 좋은 재료만을 엄선하고, 위생적인 공장 환경에서 정성껏 만듭니다.",
  cert_image: "",
  cert_1_icon: "", cert_1_title: "ISO 22000", cert_1_desc: "국제 식품안전경영시스템 인증",
  cert_2_icon: "", cert_2_title: "FDA", cert_2_desc: "미국 식품의약국 등록",
  cert_3_icon: "", cert_3_title: "HALAL", cert_3_desc: "할랄 식품 인증 획득",
  cert_4_icon: "", cert_4_title: "HACCP", cert_4_desc: "식품안전관리인증기준 적합",
  cert_5_icon: "", cert_5_title: "금속검출기", cert_5_desc: "전 제품 금속 이물질 검사 완료",
  heritage_image: "",
  heritage_label: "Brand story",
  heritage_title: "8년 연속 블루리본 맛집, 그 레시피 그대로 담았습니다",
  heritage_stat1_num: "12", heritage_stat1_unit: "년", heritage_stat1_label: "경력 셰프팀",
  heritage_stat2_num: "8", heritage_stat2_unit: "년", heritage_stat2_label: "연속 블루리본",
  heritage_stat3_num: "14", heritage_stat3_unit: "년", heritage_stat3_label: "슬런치 역사",
  heritage_body:
    "슬런치의 시작은 2011년, 홍대의 작은 샐러드 가게였습니다.\n순두부 부산물을 활용한 치즈, 소시지, 페퍼로니 등 특허 기반의 제품을 개발하며 지금은 220종이 넘는 식물성 식품을 직접 연구하고 제조하고 있습니다.",
  serving_title: "이렇게 드셔보세요",
  serving_subtitle: "캔 볶음김치를 더 맛있게 즐기는 방법",
  serving_center_image: "",
  serving_1_image: "", serving_1_title: "간편하게", serving_1_desc: "따뜻한 밥에 얹고 참기름 한 방울",
  serving_2_image: "", serving_2_title: "토핑으로", serving_2_desc: "볶음밥, 두부구이 위에 올려서",
  serving_3_image: "", serving_3_title: "면 요리와", serving_3_desc: "라면, 우동에 곁들여서",
  serving_4_image: "", serving_4_title: "캠핑에서", serving_4_desc: "캠핑 불판 위에서 간단히 데워서",
  serving_5_image: "", serving_5_title: "찌개 재료로", serving_5_desc: "김치찌개, 부대찌개 베이스로 활용",
  serving_tip: "참기름, 김가루, 깨를 뿌려 드시면 더욱 깊은 맛을 느끼실 수 있어요.",
  strength_quote: "맛있게 먹었더니, 알고 보니 건강한 한 끼",
  strength_summary_title: "슬런치 캔 볶음김치의 특별한 점 5가지",
  strength_circle1_main: "100%", strength_circle1_sub: "식물성",
  strength_circle2_main: "無", strength_circle2_sub: "젓갈",
  strength_circle3_main: "36", strength_circle3_sub: "개월 보관",
  strength_circle4_main: "No", strength_circle4_sub: "조리",
  strength_circle5_main: "HACCP", strength_circle5_sub: "인증",
  strength1_image: "", strength1_title: "100% 식물성 깔끔한 재료", strength1_desc: "젓갈, 우유, 꿀 없이 만들어 누구나 부담 없이 즐길 수 있어요.",
  strength2_image: "", strength2_title: "레토르트 캔 간편한 보관", strength2_desc: "실온에서 36개월 보관 가능.",
  strength3_image: "", strength3_title: "대파기름의 풍미", strength3_desc: "젓갈 없이도 깊은 맛을 내는 비결.",
  strength4_image: "", strength4_title: "조리 필요 없음", strength4_desc: "개봉 즉시 바로 드실 수 있어요.",
  strength5_image: "", strength5_title: "HACCP 인증 안전한 제조", strength5_desc: "식품안전관리인증 시설에서 생산합니다.",
  reveal_image: "",
  reveal_quote: "결국, 좋은 식사는 좋은 재료에서 시작됩니다.",
  reveal_body: "슬런치 캔 볶음김치는 정직한 재료와 정성스러운 조리법으로 만든 한 끼입니다.",
  gathering_image: "",
  review_title: "먹어본 분들의 이야기",
  review_subtitle: "실제 구매 후기",
  review_1: "김치를 안 좋아하는 아이도 잘 먹어요!",
  review_2: "자취생 필수템입니다",
  review_3: "캠핑갈 때 꼭 챙겨가요",
  review_4: "비건인데 드디어 김치를 먹을 수 있게 됐어요",
  review_5: "밥에 얹어 먹으면 반찬이 필요 없어요",
  review_6: "선물용으로도 좋아요",
  review_7: "재구매 3번째입니다",
  qna_title: "자주 묻는 질문",
  qna_subtitle: "궁금한 점을 확인해 보세요",
  qna_q1: "유통기한이 얼마나 되나요?",
  qna_a1: "실온 보관 36개월입니다.",
  qna_q2: "비건 제품인가요?",
  qna_a2: "네, 100% 식물성 원료만 사용합니다.",
  qna_q3: "매운맛이 강한가요?",
  qna_a3: "절제된 매운맛으로, 어린이도 먹을 수 있는 수준입니다.",
  ending_image: "",
  info_제품명: "슬런치 캔 볶음김치",
  info_원료명: "배추, 고춧가루, 대파, 마늘, 생강, 설탕, 소금",
  info_식품유형: "김치캔",
  info_내용량: "160g",
  info_내포장재질: "캔",
  info_품목보고번호: "",
};

export const SEED_SUBSCRIBE_PRODUCT: SubscribeProduct = {
  id: 1,
  code: "PV02",
  name: "로스티드 비트 카르파초",
  tier: "PREMIUM",
  diet: "비건",
  origin: "프랑스",
  cost: 3800,
  price: 12900,
  ingredients:
    "비트 300g, 발사믹 글레이즈 30ml, 아루굴라 50g, 캐슈넛 리코타 50g, 호두 30g, 올리브오일",
  tagline: "루비빛 우아함, 한 입의 프렌치 예술",
  description:
    "깊은 흙 향의 비트와 고소한 캐슈넛 리코타, 신큼한 발사믹이 어우러진 프랑스식 카르파초.",
  selling_points: [
    { title: "프렌치 비건의 정석", desc: "카르파초, 리코타, 발사믹까지 — 프랑스 고전 요리를 100% 식물성으로 완벽히 재현했어요" },
    { title: "먹는 피부관리", desc: "항산화 성분이 풍부한 비트가 피부 톤업과 컨디션 관리를 동시에 도와줍니다" },
    { title: "크리미한 만족감", desc: "캐슈넛으로 만든 비건 리코타가 치즈 못지않은 부드러운 식감을 선사해요" },
  ],
  nutrients: { kcal: 280, protein: 12, carbs: 18, fat: 14, sodium: 320 },
  allergens: ["견과류"],
  cooking_tip:
    "냉장실에서 15분 식힌 후 전자레인지 1분에 미지근하게 데우면 풍미가 살아납니다",
  hashtags: "#슬런치구독 #비건카르파초 #프렌치비건",
  info_제품명: "슬런치 로스티드 비트 카르파초",
  info_식품유형: "기타가공품(비건)",
  info_품목보고번호: "20240145013970",
  info_내용량: "350g",
  info_유통기한: "제조일로부터 12개월",
  info_제조원: "㈜슬런치 팩토리 / 대전광역시 유성구 은구비로 8",
  info_소분원: "",
  info_판매원: "㈜슬런치 팩토리(SLUNCH FACTORY) / 대전광역시 유성구 은구비로 8, 비1호",
  info_원료명:
    "비트 300g, 발사믹 글레이즈 30ml, 아루굴라 50g, 캐슈넛 리코타 50g, 호두 30g, 올리브오일",
  info_알레르기: "견과류",
  info_참고사항:
    "보관방법: 냉동보관(-18℃ 이하) / 개봉 후 즉시 조리하여 드세요 / 전자레인지 사용 가능",
  image_url: "",
  detail_url: "",
};
